# Generated by Django 2.0.2 on 2018-07-08 08:40

import json

from django.db import migrations, models


def populate_departures(apps, schema_editor):
    """ populating the Departure table from the data in
    departtures.json file"""

    try:
        with open('.\departures.json') as in_file:
            departures = json.load(in_file)
    except IOError as e:
        errno, strerror = e.args
        print("I/O error({0}): {1}".format(errno,strerror))

    #retrieving the model
    Departure = apps.get_model('departures','Departure')

    #iterating through the dictionary from the json file,
    # creating objects and saving them to the database
    for dep in departures:
        departure = Departure()
        for attr in dep.keys():
            setattr(departure, attr, dep[attr])
        departure.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    #generated by makemigrations to create the Departure model
    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('category', models.CharField(choices=[('Adventurous', 'Adventurous'), ('Classic', 'Classic'), ('Marine', 'Marine')], max_length=25)),
            ],
        ),

        #running the function to populate the dbase
        migrations.RunPython(populate_departures),
    ]
